// <auto-generated />
using MEGASuperChatBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MEGASuperChatBot.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211203110352_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("MEGASuperChatBot.CommandEntity", b =>
                {
                    b.Property<int>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CommandAnswer")
                        .HasColumnType("text");

                    b.Property<string>("CommandAuthor")
                        .HasColumnType("text");

                    b.Property<string>("CommandCreateDate")
                        .HasColumnType("text");

                    b.Property<string>("CommandDescription")
                        .HasColumnType("text");

                    b.Property<string>("CommandTrigger")
                        .HasColumnType("text");

                    b.Property<bool>("IsScript")
                        .HasColumnType("boolean");

                    b.Property<string>("ScriptName")
                        .HasColumnType("text");

                    b.Property<string>("SourcesNames")
                        .HasColumnType("text");

                    b.HasKey("CommandId");

                    b.ToTable("CommandEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
